#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-latest-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      extension_name: spatial
      ci_tools_version: main
      vcpkg_commit: d7112d1a4fb50410d3639f5f586972591d848beb
      exclude_archs: 'linux_amd64_musl'

  duckdb-latest-deploy:
    name: Deploy extension binaries
    needs: duckdb-latest-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: spatial
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      exclude_archs: 'linux_amd64_musl'
